server:
  port: 8000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/techblog
    username: root
    password: myserver
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    username: studybeginshere@gmail.com
    password: rbzqzsmivdscxrce
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true






